# Generated by Django 4.2.3 on 2023-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Medic name', max_length=50)),
                ('surname', models.CharField(blank=True, help_text='Medic surname', max_length=50)),
                ('medical_qualifications', models.CharField(choices=[('First Aid', 'First Aid'), ('Qualified first aid', 'Qualified first aid'), ('Midwife', 'Midwife'), ('Nurse', 'Nurse'), ('Paramedic', 'Paramedic'), ('Doctor', 'Doctor')], default='First aid', help_text='Qualifications of medic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.TextField(blank=True, help_text='Place for medical interview')),
                ('description', models.TextField(blank=True, help_text='Place for patient description')),
                ('diagnosis', models.CharField(blank=True, help_text='Diagnose', max_length=50)),
                ('drugs', models.CharField(blank=True, help_text='Medications given to the patient', max_length=50)),
                ('additional_info', models.TextField(blank=True, help_text='Additional info about patient treatment')),
                ('medical_staff', models.ForeignKey(default='No staff assigned', help_text='Add medic to patient', on_delete=models.SET('No staff assigned'), to='treatment.medicalstaff')),
            ],
        ),
    ]
