# Generated by Django 4.2.3 on 2023-07-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Drugs', [('ASA', 'ASA'), ('Adenosine', 'Adenosine'), ('Adrenalin', 'Adrenalin'), ('Amiodarone', 'Amiodarone'), ('Aspargin', 'Aspargin'), ('Atropine', 'Atropine'), ('Betaloc', 'Betaloc'), ('Bicarbonate', 'Bicarbonate'), ('Budesonide', 'Budesonide'), ('Buscolysin', 'Buscolysin'), ('Calcium', 'Calcium'), ('Captopril', 'Captopril'), ('Clemastine', 'Clemastine'), ('Clonazepam', 'Clonazepam'), ('Clopidogrel', 'Clopidogrel'), ('Dexaven', 'Dexaven'), ('Exacyl', 'Exacyl'), ('Fentanyl', 'Fentanyl'), ('Flumazenil', 'Flumazenil'), ('Furosemide', 'Furosemide'), ('Glucagon', 'Glucagon'), ('Glucose 20% i.v.', 'Glucose 20% i.v.'), ('Glucose 40%', 'Glucose 40%'), ('Heparin', 'Heparin'), ('Hydrocortisone', 'Hydrocortisone'), ('Hydroxyzine', 'Hydroxyzine'), ('Ibuprofen', 'Ibuprofen'), ('Ketamine', 'Ketamine'), ('Ketonal', 'Ketonal'), ('Lidocaine', 'Lidocaine'), ('Magnesium', 'Magnesium'), ('Mannitol', 'Mannitol'), ('Metoclopramide', 'Metoclopramide'), ('Midanium', 'Midanium'), ('Morphine', 'Morphine'), ('Naloxone', 'Naloxone'), ('Nitrendipine', 'Nitrendipine'), ('Nitromind', 'Nitromid'), ('No-Spa', 'No-Spa'), ('Ondansetron', 'Ondansetron'), ('Pantoprazol', 'Pantoprazol'), ('Paracetamol', 'Paracetamol'), ('Polstigmine', 'Polstigmine'), ('Propofol', 'Propofol'), ('Pyralgin', 'Pyralgin'), ('Relanium', 'Relanium'), ('Relsed', 'Relsed'), ('Rocuronium', 'Rocuronium'), ('Salbutamol', 'Salbutamol'), ('Suxamethonium', 'Suxamethonium'), ('Ticagrelor', 'Ticagrelor'), ('Torecan', 'Torecan'), ('Urapidil', 'Urapidil')]), ('Fluids', [('Aqua', 'Aqua'), ('Glucose 20%', 'Glucose 20%'), ('Glucose 5%', 'Glucose 5%'), ('NaCl 0.9%', 'NaCl 0.9%'), ('Optilyte', 'Optilyte'), ('Other', 'Other'), ('Plasmalyte', 'Plasmalyte'), ('Ringer', 'Ringer')])], help_text='Add new drug', max_length=40)),
                ('dosage_form', models.CharField(blank=True, choices=[('Pills', 'Pills'), ('Nebulizer', 'Nebulizer'), ('Injection', 'Injection'), ('Ointment / Gel', 'Ointment / Gel'), ('Areosol', 'Areosol'), ('Rectal enema', 'Rectal enema')], help_text='Dosage form of drug', max_length=20)),
                ('volume', models.CharField(blank=True, choices=[('5ml', '5ml'), ('10ml', '10ml'), ('20ml', '20ml'), ('50ml', '50ml'), ('100ml', '100ml'), ('250ml', '250ml'), ('500ml', '500ml'), ('1000ml', '1000ml')], help_text='Volume of fluid', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drugs',
            field=models.ForeignKey(blank=True, default='No drugs were given', help_text='Medications given to the patient', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='treatment.drug'),
        ),
    ]
