# Generated by Django 4.2.3 on 2023-07-13 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_vitalsign_treatment_vital_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='drugs',
            field=models.ForeignKey(blank=True, help_text='Medications given to the patient', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='treatment.drug'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='medical_staff',
            field=models.ForeignKey(help_text='Add medic to patient', on_delete=models.SET('No staff assigned'), to='treatment.medicalstaff'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='vital_sign',
            field=models.ForeignKey(blank=True, help_text='Vital signs of patient', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='treatment.vitalsign'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 13, 21, 2, 43, 987676)),
        ),
    ]
