# Generated by Django 4.2.3 on 2023-07-13 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_alter_treatment_drugs_alter_treatment_medical_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 13, 21, 4, 6, 151242)),
        ),
    ]
