# Generated by Django 4.2.3 on 2023-07-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_alter_vitalsign_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 13, 21, 9, 3, 561058)),
        ),
    ]
