# Generated by Django 4.2.3 on 2023-07-16 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0010_alter_vitalsign_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="diagnosis",
            field=models.CharField(blank=True, help_text="Diagnose?", max_length=50),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="medical_staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Add medic to patient",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treatment.medicalstaff",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="datetime",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2023, 7, 16, 9, 44, 48, 559594)
            ),
        ),
    ]
