# Generated by Django 4.2.3 on 2023-07-16 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0011_alter_treatment_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="datetime",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2023, 7, 16, 9, 45, 1, 733404)
            ),
        ),
    ]
