# Generated by Django 4.2.3 on 2023-08-06 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0014_alter_vitalsign_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="additional_info",
        ),
    ]
