# Generated by Django 4.2.3 on 2023-08-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0017_alter_treatment_drugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="vital_sign",
            field=models.ForeignKey(
                blank=True,
                help_text="Vital signs of patient",
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="treatment.vitalsign",
            ),
        ),
    ]
