# Generated by Django 4.2.3 on 2023-08-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0020_alter_treatment_drugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="drugs",
            field=models.ForeignKey(
                blank=True,
                help_text="Medications given to the patient",
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment",
                to="treatment.drug",
            ),
        ),
    ]
