# Generated by Django 4.2.3 on 2023-08-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0021_alter_treatment_drugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="medical_staff",
        ),
        migrations.AddField(
            model_name="treatment",
            name="medical_staff",
            field=models.ManyToManyField(
                blank=True, help_text="Add medic to patient", null=True, to="treatment.medicalstaff"
            ),
        ),
    ]
