# Generated by Django 4.2.3 on 2023-08-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0022_remove_treatment_medical_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="drugs",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="medical_staff",
        ),
        migrations.AddField(
            model_name="treatment",
            name="drugs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Medications given to the patient",
                max_length=50,
                null=True,
                related_name="treatment",
                to="treatment.drug",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="medical_staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Add medic to patient",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treatment.medicalstaff",
            ),
        ),
    ]
