# Generated by Django 4.2.3 on 2023-08-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0024_remove_treatment_drugs_drug_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                help_text="Add drug",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drug",
                to="treatment.treatment",
            ),
        ),
    ]
