# Generated by Django 4.2.3 on 2023-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0025_alter_drug_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="dose",
            field=models.IntegerField(blank=True, help_text="Dose of drug", null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="unit",
            field=models.CharField(
                blank=True, choices=[("g", "g"), ("mg", "mg"), ("mcg", "mcg")], help_text="Choose unit", max_length=3
            ),
        ),
    ]
