# Generated by Django 4.2.3 on 2023-08-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0027_alter_drug_dose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("g", "g"), ("mg", "mg"), ("mcg", "mcg")],
                default="mg",
                help_text="Choose unit",
                max_length=3,
            ),
        ),
    ]
