# Generated by Django 4.2.3 on 2023-08-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0028_alter_drug_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="dose",
            field=models.FloatField(help_text="Dose of drug", null=True),
        ),
        migrations.AlterField(
            model_name="drug",
            name="name",
            field=models.CharField(
                choices=[
                    (
                        "Drugs",
                        [
                            ("ASA", "ASA"),
                            ("Adenosine", "Adenosine"),
                            ("Adrenalin", "Adrenalin"),
                            ("Amiodarone", "Amiodarone"),
                            ("Aspargin", "Aspargin"),
                            ("Atropine", "Atropine"),
                            ("Betaloc", "Betaloc"),
                            ("Bicarbonate", "Bicarbonate"),
                            ("Budesonide", "Budesonide"),
                            ("Buscolysin", "Buscolysin"),
                            ("Calcium", "Calcium"),
                            ("Captopril", "Captopril"),
                            ("Clemastine", "Clemastine"),
                            ("Clonazepam", "Clonazepam"),
                            ("Clopidogrel", "Clopidogrel"),
                            ("Dexaven", "Dexaven"),
                            ("Exacyl", "Exacyl"),
                            ("Fentanyl", "Fentanyl"),
                            ("Flumazenil", "Flumazenil"),
                            ("Furosemide", "Furosemide"),
                            ("Glucagon", "Glucagon"),
                            ("Glucose 20% i.v.", "Glucose 20% i.v."),
                            ("Glucose 40%", "Glucose 40%"),
                            ("Heparin", "Heparin"),
                            ("Hydrocortisone", "Hydrocortisone"),
                            ("Hydroxyzine", "Hydroxyzine"),
                            ("Ibuprofen", "Ibuprofen"),
                            ("Ketamine", "Ketamine"),
                            ("Ketonal", "Ketonal"),
                            ("Lidocaine", "Lidocaine"),
                            ("Magnesium", "Magnesium"),
                            ("Mannitol", "Mannitol"),
                            ("Metoclopramide", "Metoclopramide"),
                            ("Midanium", "Midanium"),
                            ("Morphine", "Morphine"),
                            ("Naloxone", "Naloxone"),
                            ("Nitrendipine", "Nitrendipine"),
                            ("Nitromind", "Nitromid"),
                            ("No-Spa", "No-Spa"),
                            ("Ondansetron", "Ondansetron"),
                            ("Pantoprazol", "Pantoprazol"),
                            ("Paracetamol", "Paracetamol"),
                            ("Polstigmine", "Polstigmine"),
                            ("Propofol", "Propofol"),
                            ("Pyralgin", "Pyralgin"),
                            ("Relanium", "Relanium"),
                            ("Relsed", "Relsed"),
                            ("Rocuronium", "Rocuronium"),
                            ("Salbutamol", "Salbutamol"),
                            ("Suxamethonium", "Suxamethonium"),
                            ("Ticagrelor", "Ticagrelor"),
                            ("Torecan", "Torecan"),
                            ("Urapidil", "Urapidil"),
                        ],
                    ),
                    (
                        "Fluids",
                        [
                            ("Aqua", "Aqua"),
                            ("Glucose 20%", "Glucose 20%"),
                            ("Glucose 5%", "Glucose 5%"),
                            ("NaCl 0.9%", "NaCl 0.9%"),
                            ("Optilyte", "Optilyte"),
                            ("Other", "Other"),
                            ("Plasmalyte", "Plasmalyte"),
                            ("Ringer", "Ringer"),
                        ],
                    ),
                ],
                help_text="Add new drug",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="unit",
            field=models.CharField(
                choices=[("g", "g"), ("mg", "mg"), ("mcg", "mcg")], default="mg", help_text="Choose unit", max_length=3
            ),
        ),
    ]
