# Generated by Django 4.2.3 on 2023-08-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0029_alter_drug_dose_alter_drug_name_alter_drug_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="volume",
        ),
        migrations.AlterField(
            model_name="drug",
            name="unit",
            field=models.CharField(
                choices=[("g", "g"), ("mg", "mg"), ("mcg", "mcg"), ("ml", "ml")],
                default="mg",
                help_text="Choose unit",
                max_length=3,
            ),
        ),
    ]
