# Generated by Django 4.2.3 on 2023-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0031_remove_treatment_vital_sign_vitalsign_treatment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsign",
            name="extra_value",
            field=models.IntegerField(blank=True, help_text="Additional value", null=True),
        ),
    ]
