# Generated by Django 4.2.3 on 2023-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0032_vitalsign_extra_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="extra_value",
            field=models.IntegerField(blank=True, help_text="DIA BP value", null=True),
        ),
    ]
