# Generated by Django 4.2.3 on 2023-08-21 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0033_alter_vitalsign_extra_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vitalsign",
            name="additional_info",
        ),
    ]
