# Generated by Django 4.2.3 on 2023-08-22 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0035_remove_vitalsign_extra_value_remove_vitalsign_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="bp_dia",
            field=models.IntegerField(
                blank=True,
                help_text="Value of diastolic blood pressure",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "BP cannot be under zero"),
                    django.core.validators.MaxValueValidator(350, "Max diastolic BP is limited to 250mmHg"),
                ],
                verbose_name="Diastolic blood pressure",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="bp_sys",
            field=models.IntegerField(
                blank=True,
                help_text="Value of systolic blood pressure",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "BP cannot be under zero"),
                    django.core.validators.MaxValueValidator(350, "Max systolic BP is limited to 350mmHg"),
                ],
                verbose_name="Systolic blood pressure",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="hr",
            field=models.IntegerField(
                blank=True,
                help_text="Heart rate value",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "HR cannot be under zero"),
                    django.core.validators.MaxValueValidator(350, "Max HR is limited to 350/min "),
                ],
                verbose_name="Heart rate",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="spo2",
            field=models.IntegerField(
                blank=True,
                help_text="Saturation value",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "SpO2 cannot be under 0%"),
                    django.core.validators.MaxValueValidator(100, "SpO2 cannot be over 100%"),
                ],
                verbose_name="Saturation",
            ),
        ),
    ]
