# Generated by Django 4.2.3 on 2023-08-22 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0036_alter_vitalsign_bp_dia_alter_vitalsign_bp_sys_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsign",
            name="gcs",
            field=models.IntegerField(
                blank=True,
                help_text="Patient GSC level",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3, "Minimum GCS level is 3"),
                    django.core.validators.MaxValueValidator(15, "Maximum GCS level is 15"),
                ],
                verbose_name="Glasgow Coma Scale",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="glycemia",
            field=models.IntegerField(
                blank=True,
                help_text="Patient blood glucose level in mg%",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "Glycemia level is limited to 900mg%"),
                    django.core.validators.MaxValueValidator(900, "Glycemia level cannot be under 0mg%"),
                ],
                verbose_name="Glucose level",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="Patient temperature in *C",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(13, "Temperature limit is set to 13*C"),
                    django.core.validators.MaxValueValidator(45, "Temperature limit is set to 45*C"),
                ],
                verbose_name="Temperature",
            ),
        ),
    ]
