# Generated by Django 4.2.3 on 2023-08-22 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0037_vitalsign_gcs_vitalsign_glycemia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="spo2",
            field=models.IntegerField(
                blank=True,
                help_text="Heart rate value",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "HR cannot be under zero"),
                    django.core.validators.MaxValueValidator(350, "Max HR is limited to 350/min "),
                ],
                verbose_name="Heart rate",
            ),
        ),
    ]
