# Generated by Django 4.2.3 on 2023-08-22 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0038_alter_vitalsign_spo2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vitalsign",
            name="spo2",
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="sao2",
            field=models.IntegerField(
                blank=True,
                help_text="Saturation value",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "SaO2 cannot be under zero"),
                    django.core.validators.MaxValueValidator(100, "Max SaO2 is limited to 100%"),
                ],
                verbose_name="Saturation",
            ),
        ),
    ]
