# Generated by Django 4.2.3 on 2023-08-22 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0040_alter_vitalsign_sao2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="sao2",
            field=models.IntegerField(
                blank=True,
                help_text="Saturation value",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30, "SaO2 too low"),
                    django.core.validators.MaxValueValidator(100, "Max SaO2 is limited to 100"),
                ],
                verbose_name="Saturation",
            ),
        ),
    ]
