# Generated by Django 4.2.3 on 2023-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0043_alter_vitalsign_glycemia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="diagnosis",
            field=models.CharField(blank=True, help_text="Diagnose?", max_length=100),
        ),
    ]
