# Generated by Django 4.2.3 on 2023-07-13 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 16, 47, 48, 68258), help_text='Date of patient admission'),
        ),
    ]
