# Generated by Django 4.2.3 on 2023-07-16 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0010_alter_patient_admission_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="e_mail",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 16, 9, 44, 48, 562130),
                help_text="Date of patient admission",
            ),
        ),
    ]
