# Generated by Django 4.2.3 on 2023-07-16 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_alter_patient_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 16, 15, 17, 39, 833376),
                help_text="Date of patient admission",
            ),
        ),
    ]
