# Generated by Django 4.2.3 on 2023-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0013_alter_patient_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date of patient admission"
            ),
        ),
    ]
