# Generated by Django 4.2.3 on 2023-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0014_alter_vitalsign_datetime"),
        ("patients", "0015_alter_patient_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="treatment",
            field=models.OneToOneField(
                blank=True,
                help_text="Add treatment",
                null=True,
                on_delete=models.SET("No treatment"),
                related_name="patient",
                to="treatment.treatment",
            ),
        ),
    ]
