# Generated by Django 4.2.3 on 2023-07-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_start_date"),
        ("patients", "0016_alter_patient_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="event",
            field=models.ForeignKey(
                default="No event assigned",
                help_text="Set event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="events.event",
            ),
        ),
    ]
