# Generated by Django 4.2.3 on 2023-07-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0014_alter_vitalsign_datetime"),
        ("patients", "0017_alter_patient_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="authorized_person",
            field=models.OneToOneField(
                blank=True,
                default="No authorized person",
                help_text="Set authorized person",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="patients.authorizedperson",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="treatment",
            field=models.OneToOneField(
                blank=True,
                help_text="Add treatment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="treatment.treatment",
            ),
        ),
    ]
