# Generated by Django 4.2.3 on 2023-07-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_start_date"),
        ("patients", "0018_alter_patient_authorized_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="authorized_person",
            field=models.OneToOneField(
                blank=True,
                help_text="Set authorized person",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="patients.authorizedperson",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="event",
            field=models.ForeignKey(
                help_text="Set event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="events.event",
            ),
        ),
    ]
