# Generated by Django 4.2.3 on 2023-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0019_alter_patient_authorized_person_alter_patient_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(default="Active", max_length=20),
        ),
    ]
