# Generated by Django 4.2.3 on 2023-07-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0020_patient_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(
                default="NNb'Z\\x1f \\x9f\\xe4'",
                help_text="Patient name",
                max_length=50,
            ),
        ),
    ]
