# Generated by Django 4.2.3 on 2023-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0021_alter_patient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(
                default="NN59852", help_text="Patient name", max_length=50
            ),
        ),
    ]
