# Generated by Django 4.2.3 on 2023-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0024_remove_patient_sex_alter_patient_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(
                default="07-22-2023 10:08", help_text="Date of patient admission"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="bed_number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No bed", "No bed"),
                    ("ALS", "ALS"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                    ("25", "25"),
                ],
                default="No bed",
                help_text="Bed number in hospital",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="surname",
            field=models.CharField(
                default="NN 07-22-2023 10:08:23",
                help_text="Patient surname",
                max_length=50,
            ),
        ),
    ]
