# Generated by Django 4.2.3 on 2023-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0025_alter_patient_admission_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizedperson",
            name="name",
            field=models.CharField(help_text="Person name", max_length=50),
        ),
        migrations.AlterField(
            model_name="authorizedperson",
            name="surname",
            field=models.CharField(help_text="Person surname", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(default="08-05-2023 22:11", help_text="Date of patient admission"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="surname",
            field=models.CharField(default="NN 08-05-2023 22:11:57", help_text="Patient surname", max_length=50),
        ),
    ]
