# Generated by Django 4.2.3 on 2023-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0026_alter_authorizedperson_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(default="08-06-2023 11:16", help_text="Date of patient admission"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="surname",
            field=models.CharField(default="NN 08-06-2023 11:16:12", help_text="Patient surname", max_length=50),
        ),
    ]
