# Generated by Django 4.2.3 on 2023-09-03 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0033_alter_patient_admission_date_alter_patient_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date of patient admission"),
        ),
    ]
