# Generated by Django 4.2.3 on 2023-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0034_alter_patient_admission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("RED", "RED"), ("YELLOW", "YELLOW"), ("GREEN", "GREEN")],
                help_text="Priority",
                null=True,
                max_length=6,
            ),
        ),
    ]
