# Generated by Django 4.2.3 on 2023-09-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0035_patient_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="PESEL",
            field=models.BigIntegerField(blank=True, help_text="Patient PESEL number", null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.BigIntegerField(blank=True, help_text="Patient phone number", null=True),
        ),
    ]
