# Generated by Django 4.2.3 on 2023-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0036_alter_patient_pesel_alter_patient_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("RED", "RED"), ("YELLOW", "YELLOW"), ("GREEN", "GREEN")],
                help_text="Priority",
                max_length=6,
                null=True,
            ),
        ),
    ]
