MEDICAL_QUALIFICATIONS = [
    ("First Aid", "First Aid"),
    ("Qualified first aid", "Qualified first aid"),
    ("Midwife", "Midwife"),
    ("Nurse", "Nurse"),
    ("Paramedic", "Paramedic"),
    ("Doctor", "Doctor"),
]

DRUGS = sorted(
    [
        ("Adrenalin", "Adrenalin"),
        ("ASA", "ASA"),
        ("Ketonal", "Ketonal"),
        ("Ibuprofen", "Ibuprofen"),
        ("Pyralgin", "Pyralgin"),
        ("Paracetamol", "Paracetamol"),
        ("Morphine", "Morphine"),
        ("Fentanyl", "Fentanyl"),
        ("Naloxone", "Naloxone"),
        ("Budesonide", "Budesonide"),
        ("Hydrocortisone", "Hydrocortisone"),
        ("Dexaven", "Dexaven"),
        ("Relanium", "Relanium"),
        ("Relsed", "Relsed"),
        ("Clonazepam", "Clonazepam"),
        ("Midanium", "Midanium"),
        ("Flumazenil", "Flumazenil"),
        ("Atropine", "Atropine"),
        ("Adenosine", "Adenosine"),
        ("Amiodarone", "Amiodarone"),
        ("Lidocaine", "Lidocaine"),
        ("Salbutamol", "Salbutamol"),
        ("Urapidil", "Urapidil"),
        ("Betaloc", "Betaloc"),
        ("No-Spa", "No-Spa"),
        ("Nitromind", "Nitromid"),
        ("Clopidogrel", "Clopidogrel"),
        ("Ticagrelor", "Ticagrelor"),
        ("Heparin", "Heparin"),
        ("Torecan", "Torecan"),
        ("Metoclopramide", "Metoclopramide"),
        ("Furosemide", "Furosemide"),
        ("Mannitol", "Mannitol"),
        ("Hydroxyzine", "Hydroxyzine"),
        ("Magnesium", "Magnesium"),
        ("Clemastine", "Clemastine"),
        ("Bicarbonate", "Bicarbonate"),
        ("Captopril", "Captopril"),
        ("Glucagon", "Glucagon"),
        ("Glucose 20% i.v.", "Glucose 20% i.v."),
        ("Glucose 40%", "Glucose 40%"),
        ("Exacyl", "Exacyl"),
        ("Ketamine", "Ketamine"),
        ("Polstigmine", "Polstigmine"),
        ("Ondansetron", "Ondansetron"),
        ("Buscolysin", "Buscolysin"),
        ("Suxamethonium", "Suxamethonium"),
        ("Calcium", "Calcium"),
        ("Propofol", "Propofol"),
        ("Pantoprazol", "Pantoprazol"),
        ("Nitrendipine", "Nitrendipine"),
        ("Rocuronium", "Rocuronium"),
        ("Aspargin", "Aspargin"),
    ]
)

FLUIDS = sorted(
    [
        ("Other", "Other"),
        ("Glucose 20%", "Glucose 20%"),
        ("Glucose 5%", "Glucose 5%"),
        ("NaCl 0.9%", "NaCl 0.9%"),
        ("Optilyte", "Optilyte"),
        ("Ringer", "Ringer"),
        ("Plasmalyte", "Plasmalyte"),
        ("Aqua", "Aqua"),
    ]
)

DRUG_AND_FLUID_CHOICES = [("Drugs", DRUGS), ("Fluids", FLUIDS)]

DRUG_DOSAGE_FORM = [
    ("Pills", "Pills"),
    ("Nebulizer", "Nebulizer"),
    ("Injection", "Injection"),
    ("Ointment / Gel", "Ointment / Gel"),
    ("Areosol", "Areosol"),
    ("Rectal enema", "Rectal enema"),
]

UNIT_CHOICES = [("g", "g"), ("mg", "mg"), ("mcg", "mcg"), ("ml", "ml")]

ICD_10_DISEASES = {
    "Myocardial Infarction": "I21.9",
    "Stroke": "I63.9",
    "Cardiac Arrest": "I46.9",
    "Respiratory Distress": "R06.0",
    "Traumatic Brain Injury": "S06.9",
    "Hemorrhage": "R58",
    "Anaphylaxis": "T78.2",
    "Diabetic Emergency": "E10.9",
    "Seizures": "R56.9",
    "Respiratory Failure": "J96.9",
    "Asthma Exacerbation": "J45.901",
    "Hypertensive Crisis": "I10",
    "COPD Exacerbation": "J44.1",
    "Pneumonia": "J18.9",
    "Choking": "T17",
    "Drug Overdose": "T40.9",
    "Shock": "R57.9",
    "Dehydration": "E86",
    "Sepsis": "A41.9",
    "Burns": "T31.9",
    "Poisoning": "T51",
    "Fractures": "S22.9",
    "Head Injury": "S09.9",
    "Chest Pain": "R07.9",
    "Shortness of Breath": "R06.02",
    "Hypoglycemia": "E16.2",
    "Hyperglycemia": "E10.9",
    "Pulmonary Embolism": "I26.90",
    "Allergic Reaction": "T78.4",
    "Cerebral Hemorrhage": "I61.9",
    "Sudden Cardiac Death": "I46.9",
    "Appendicitis": "K35.9",
    "Atrial Fibrillation": "I48.91",
    "Gastrointestinal Bleeding": "K92.2",
    "Aortic Dissection": "I71.9",
    "Pulmonary Edema": "J81",
    "Aortic Aneurysm": "I71.9",
    "Syncope": "R55",
    "Pneumothorax": "J93.9",
    "Drowning": "T75.1",
    "Hypothermia": "T68",
    "Heat Stroke": "T67",
    "Electrocution": "T75.4",
    "Psychiatric Crisis": "F99",
    "Suicidal Ideation": "R45.851",
    "Opioid Overdose": "T40.0",
    "Alcohol Intoxication": "F10.9",
    "Asthma Attack": "J45.901",
    "Hyperventilation": "R06.4",
    "Hypotension": "I95.9",
    "Cyanosis": "R23.0",
    "Dysrhythmia": "I49.9",
    "Abdominal Pain": "R10.9",
    "Severe Bleeding": "R58",
    "Aspiration": "T17",
    "Status Epilepticus": "G41.9",
    "Cluster Headache": "G44.0",
    "Trigeminal Neuralgia": "G50.0",
    "Intracerebral Hemorrhage": "I61.9",
    "Heat Exhaustion": "T67.0",
    "Cocaine Overdose": "T40.5",
    "Meningitis": "G03.9",
    "Encephalitis": "G04.9",
    "Stroke (Ischemic)": "I63.9",
    "Stroke (Hemorrhagic)": "I61.9",
    "Hypoglycemic Emergency": "E16.2",
    "Hyperosmolar Hyperglycemic State (HHS)": "E11.1",
    "Hypertensive Emergency": "I10",
    "Altered Mental Status": "R41.82",
    "Overdose (Multiple Substances)": "T50.9",
    "Intoxication (Other Substances)": "F10.9",
    "Acute Kidney Injury": "N17.9",
    "Seizure (Generalized)": "G40.9",
    "Seizure (Partial)": "G40.9",
    "Acute Respiratory Distress Syndrome (ARDS)": "J80",
    "Chronic Obstructive Pulmonary Disease (COPD) Exacerbation": "J44.1",
    "Asthma Exacerbation (Other)": "J45.901",
    "Acute Coronary Syndrome": "I24.9",
    "Abdominal Aortic Aneurysm": "I71.9",
    "Aortic Stenosis": "I35.0",
    "Aortic Regurgitation": "I06.9",
    "Mitral Stenosis": "I05.9",
    "Mitral Regurgitation": "I34.9",
    "Tricuspid Stenosis": "I07.0",
    "Tricuspid Regurgitation": "I06.9",
    "Pulmonary Stenosis": "I37.0",
    "Pulmonary Regurgitation": "I37.1",
    "Cardiomyopathy (Dilated)": "I42.0",
    "Cardiomyopathy (Hypertrophic)": "I42.2",
    "Cardiomyopathy (Restrictive)": "I42.9",
    "Cardiomyopathy (Arrhythmogenic)": "I42.7",
    "Myocarditis": "I40.9",
    "Pericarditis (Acute)": "I30.9",
    "Pericarditis (Constrictive)": "I31.9",
    "Pericarditis (Effusive)": "I32.9",
    "Hypertension (High Blood Pressure)": "I10",
    "Cardiogenic Shock": "R57.0",
    "Heart Rhythm Disorders (Atrial Fibrillation)": "I48.91",
    "Heart Rhythm Disorders (Atrial Flutter)": "I48.91",
    "Heart Rhythm Disorders (Ventricular Fibrillation)": "I49.02",
    "Heart Rhythm Disorders (Ventricular Tachycardia)": "I47.2",
    "Heart Rhythm Disorders (Bradyarrhythmia)": "I49.9",
    "Heart Rhythm Disorders (Supraventricular Tachycardia)": "I47.9",
    "Hypertrophic Obstructive Cardiomyopathy (HOCM)": "I42.2",
    "Dilated Cardiomyopathy (DCM)": "I42.0",
    "Arrhythmogenic Right Ventricular Cardiomyopathy (ARVC)": "I42.7",
    "Infective Endocarditis": "I33.9",
    "Non-infective Endocarditis": "I38.9",
    "Coronary Artery Disease (CAD)": "I25.10",
    "Congestive Heart Failure (CHF)": "I50.9",
    "Heart Valve Disease (Valvular Heart Disease)": "I08.9",
    "Aortic Aneurysm (Non-abdominal)": "I71.9",
    "Aortic Aneurysm (Thoracic)": "I71.9",
    "Aortic Aneurysm (Abdominal)": "I71.9",
    "Pulmonary Embolism (Recurrent)": "I26.92",
    "Hemoptysis": "R04.2",
    "Pleural Effusion (Malignant)": "J91.0",
    "Rib Fracture (Multiple)": "S22.9",
    "Torn Aorta": "I71.9",
    "Pulmonary Hypertension (Secondary)": "I27.0",
    "Pulmonary Hypertension (Primary)": "I27.0",
    "Pulmonary Hypertension (Other)": "I27.8",
    "Pulmonary Hypertension (Unspecified)": "I27.9",
    "Pulmonary Edema (Non-cardiogenic)": "J81",
    "Embolism (Other)": "I74.9",
    "Chronic Thromboembolic Pulmonary Hypertension (CTEPH)": "I27.8",
    "Pneumonia (Bacterial)": "J18.9",
    "Pneumonia (Viral)": "J12.9",
    "Pneumonia (Aspiration)": "J69.0",
    "Bronchitis": "J40",
    "Tuberculosis": "A15.9",
    "Pulmonary Hemorrhage": "R04.2",
    "Bronchiectasis": "J47",
    "Bronchiolitis": "J21.9",
    "Laryngitis": "J04.9",
    "Croup": "J05.0",
    "Pleural Effusion": "J91.0",
}


def icd_10_choices(icd_diseases: dict = ICD_10_DISEASES) -> list:
    icd_choices = []
    for disease, code in icd_diseases.items():
        icd_choices.append((disease + " " + code, disease + " " + code))
    return sorted(icd_choices)
