# Generated by Django 4.2.3 on 2024-01-08 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("name", models.CharField(default="Event", help_text="Enter event name", max_length=100)),
                ("description", models.CharField(blank=True, help_text="Enter description", max_length=200, null=True)),
                (
                    "localization",
                    models.CharField(blank=True, help_text="Enter localization", max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Preparing", "Preparing"), ("In progress", "In progress"), ("Ended", "Ended")],
                        default="Preparing",
                        max_length=20,
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
