# Generated by Django 4.2.3 on 2023-07-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(
                blank=True, help_text="Enter description", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="localization",
            field=models.CharField(
                blank=True, help_text="Enter localization", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(
                default="Default event", help_text="Enter event name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Preparing", "Preparing"),
                    ("In progress", "In progress"),
                    ("Ended", "Ended"),
                ],
                default="Preparing",
                max_length=20,
            ),
        ),
    ]
