# Generated by Django 4.2.3 on 2023-07-20 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 7, 20)),
        ),
    ]
