# Generated by Django 4.2.3 on 2023-08-31 14:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="localization",
            field=models.CharField(blank=True, help_text="Enter localization", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 8, 31)),
        ),
    ]
